### ISSUE TITLE
Work?

### ISSUE THREAD

**Issue by Driesboy** [luca28pet/MultiInventory#1]

**Comment by TomasOlsson** [comment]
try it?

**Comment by Driesboy** [comment]
Ok i try
Op 12-dec.-2015 21:36 schreef "TomasOlsson" <notifications@github.com>:

**Comment by fycarman** [comment]
It doesn't work for now.

**Comment by Driesboy** [comment]
Ok
Op 13-dec.-2015 12:23 schreef "fycarman" <notifications@github.com>:
